[package]
name = "eg_foreman"
version = "0.1.0"
authors = ["yukihirop <te108186@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
crossbeam-channel = "0.5.0"
nix = "0.19.0"
signal-hook = "0.1.16"
